package sudoku.example.com.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import sudoku.example.com.model.SudokuBoards;

import sudoku.example.com.model.SudokuBoardsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sudokuBoardsDaoConfig;

    private final SudokuBoardsDao sudokuBoardsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sudokuBoardsDaoConfig = daoConfigMap.get(SudokuBoardsDao.class).clone();
        sudokuBoardsDaoConfig.initIdentityScope(type);

        sudokuBoardsDao = new SudokuBoardsDao(sudokuBoardsDaoConfig, this);

        registerDao(SudokuBoards.class, sudokuBoardsDao);
    }
    
    public void clear() {
        sudokuBoardsDaoConfig.getIdentityScope().clear();
    }

    public SudokuBoardsDao getSudokuBoardsDao() {
        return sudokuBoardsDao;
    }

}
