package sudoku.example.com.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUDOKU_BOARDS".
 */
public class SudokuBoards {

    private Long id;
    /** Not-null value. */
    private String visible_numbers;
    /** Not-null value. */
    private String solution;
    /** Not-null value. */
    private String level;
    private String users_solution;
    private String users_suggestions;
    private Boolean board_used;

    public SudokuBoards() {
    }

    public SudokuBoards(Long id) {
        this.id = id;
    }

    public SudokuBoards(Long id, String visible_numbers, String solution, String level, String users_solution, String users_suggestions, Boolean board_used) {
        this.id = id;
        this.visible_numbers = visible_numbers;
        this.solution = solution;
        this.level = level;
        this.users_solution = users_solution;
        this.users_suggestions = users_suggestions;
        this.board_used = board_used;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getVisible_numbers() {
        return visible_numbers;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVisible_numbers(String visible_numbers) {
        this.visible_numbers = visible_numbers;
    }

    /** Not-null value. */
    public String getSolution() {
        return solution;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSolution(String solution) {
        this.solution = solution;
    }

    /** Not-null value. */
    public String getLevel() {
        return level;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLevel(String level) {
        this.level = level;
    }

    public String getUsers_solution() {
        return users_solution;
    }

    public void setUsers_solution(String users_solution) {
        this.users_solution = users_solution;
    }

    public String getUsers_suggestions() {
        return users_suggestions;
    }

    public void setUsers_suggestions(String users_suggestions) {
        this.users_suggestions = users_suggestions;
    }

    public Boolean getBoard_used() {
        return board_used;
    }

    public void setBoard_used(Boolean board_used) {
        this.board_used = board_used;
    }

}
